# -*- coding: utf-8 -*-
"""ex4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MOZt1yKFyo-pcURtE-EnFcvcTdH1UHef
"""

import pandas as pd

# Load the dataset
url = "/content/car_evaluation.csv"
columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"]
df = pd.read_csv(url, names=columns)

# Data Exploration
print("Initial Overview:")
print(df.head())

print("\nData Types and Missing Values:")
print(df.info())

print("\nClass Distribution:")
print(df["class"].value_counts())

print("\nAttribute Analysis:")
print(df.describe())

df.replace("?", pd.NA, inplace=True)  # Replace "?" with NaN for easier handling
print("\nHandling Missing Values:")
print(df.isna().sum())

df_encoded = pd.get_dummies(df, columns=["buying", "maint", "doors", "persons", "lug_boot", "safety"])
print("\nConverting Categorical to Numeric:")
print(df_encoded.head())

df_cleaned = df_encoded.drop_duplicates()
print("\nChecking Data Integrity:")
print("Original Length:", len(df_encoded))
print("Cleaned Length:", len(df_cleaned))

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
df_cleaned["class"].value_counts().plot(kind="bar", color="skyblue")
plt.title("Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 8))
correlation_matrix = df_cleaned.corr()
plt.imshow(correlation_matrix, cmap="coolwarm", interpolation="none")
plt.colorbar()
plt.xticks(range(len(correlation_matrix)), correlation_matrix.columns, rotation=45)
plt.yticks(range(len(correlation_matrix)), correlation_matrix.columns)
plt.title("Correlation Matrix Heatmap")
plt.show()